using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using MTM_Waitlist.Module_Core.Contracts.Services;
using MTM_Waitlist.Module_Core.Models;
using MTM_Waitlist.Module_Shared.Models;
using MTM_Waitlist.Module_Shared.ViewModels;

namespace MTM_Waitlist.Module_Shared.Views;

public sealed partial class ControlInspectorDetailPage : Page
{
    private readonly IReportPrintService _reportPrintService;

    public ControlInspectorDetailViewModel ViewModel { get; }

    public ControlInspectorDetailPage()
    {
        ViewModel = App.GetService<ControlInspectorDetailViewModel>();
        _reportPrintService = App.GetService<IReportPrintService>();
        InitializeComponent();
    }

    private void OnPageLoaded(object sender, RoutedEventArgs e)
    {
        _reportPrintService.Register(App.MainWindow);
        PrintButton.IsEnabled = _reportPrintService.IsRegistered;
    }

    private void OnPageUnloaded(object sender, RoutedEventArgs e)
    {
        _reportPrintService.Unregister();
    }

    private async void OnPrintClick(object sender, RoutedEventArgs e)
    {
        if (!_reportPrintService.IsRegistered)
        {
            await ShowPrintMessageAsync(
                "Printing unavailable",
                "Printing could not be initialized for this window.");
            return;
        }

        var report = BuildReport(ViewModel.Detail);
        var printed = await _reportPrintService.PrintAsync(App.MainWindow, report);
        if (!printed)
        {
            await ShowPrintMessageAsync(
                "Printing unavailable",
                "Printing is not supported on this device or can't proceed right now.");
        }
    }

    private static PrintableReport BuildReport(ControlInspectorDetail? detail)
    {
        var sections = new List<PrintableReportSection>();
        foreach (var section in detail?.Sections ?? Array.Empty<ControlInspectorSection>())
        {
            if (string.Equals(section.Title, "Associated files", StringComparison.OrdinalIgnoreCase))
            {
                sections.Add(new PrintableReportSection
                {
                    Title = section.Title,
                    Lines = section.Fields
                        .Select(static field => field.Value)
                        .Where(static value => !string.IsNullOrWhiteSpace(value))
                        .ToArray(),
                });
                continue;
            }

            sections.Add(new PrintableReportSection
            {
                Title = section.Title,
                Fields = section.Fields
                    .Select(static field => new PrintableReportField
                    {
                        Label = field.Label,
                        Value = field.Value,
                    })
                    .ToArray(),
            });
        }

        return new PrintableReport
        {
            Title = detail?.Title ?? "Control details",
            Subtitle = detail?.Summary ?? string.Empty,
            Sections = sections,
            FooterLines = new[]
            {
                "Generated by MTM Waitlist Control Inspector",
                "Opened with Ctrl+Alt+Right-Click on a tracked control.",
            },
        };
    }

    private async Task ShowPrintMessageAsync(string title, string content)
    {
        var dialog = new ContentDialog
        {
            Title = title,
            Content = content,
            PrimaryButtonText = "OK",
            XamlRoot = XamlRoot,
        };
        await dialog.ShowAsync();
    }
}
