using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;

using MTM_Waitlist.Module_Core.Contracts.Services;
using MTM_Waitlist.Module_Core.Helpers;
using MTM_Waitlist.ViewModels;
using MTM_Waitlist.Module_Waitlist.Models;
using MTM_Waitlist.Module_Waitlist.ViewModels;

using Windows.System;

namespace MTM_Waitlist.Module_Core.Views;

// TODO: Update NavigationViewItem titles and icons in ShellPage.xaml.
public sealed partial class ShellPage : Page
{
    private readonly IStartupShellStateService _startupShellStateService;

    public ShellViewModel ViewModel
    {
        get;
    }

    public ShellPage(
        ShellViewModel viewModel,
        IStartupShellStateService startupShellStateService)
    {
        ViewModel = viewModel;
        _startupShellStateService = startupShellStateService;
        InitializeComponent();

        ViewModel.NavigationService.Frame = NavigationFrame;
        ViewModel.NavigationViewService.Initialize(NavigationViewControl);
        NavigationFrame.Navigated += NavigationFrame_Navigated;
        _startupShellStateService.StateChanged += OnStartupShellStateChanged;
        ApplyStartupShellState();
    }

    private void OnLoaded(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        ViewModel.RefreshUserInfo();
        SyncMyRequestsVisibility();
        ApplyNavigationItemSizing();

        if (AppTitleBar is null || AppTitleBarText is null)
        {
            StartupDebugLog.Info("ShellPage", "Title bar elements were unavailable on load.");
            return;
        }

        // TODO: Set the title bar icon by updating /Assets/Packaging/window-icon.ico.
        // A custom title bar is required for full window theme and Mica support.
        // https://docs.microsoft.com/windows/apps/develop/title-bar?tabs=winui3#full-customization
        App.MainWindow.ExtendsContentIntoTitleBar = true;
        App.MainWindow.SetTitleBar(AppTitleBar);
        App.AppTitlebar = AppTitleBarText as UIElement;
        AppTitleBarText.Text = "AppDisplayName".GetLocalized();
        TitleBarHelper.UpdateTitleBar(App.MainWindow, RequestedTheme);

        KeyboardAccelerators.Add(BuildKeyboardAccelerator(VirtualKey.Left, VirtualKeyModifiers.Menu));
        KeyboardAccelerators.Add(BuildKeyboardAccelerator(VirtualKey.GoBack));

        Unloaded += ShellPage_Unloaded;
    }

    /// <summary>
    /// Gives the control's own Settings entry the same label size as the items this page declares.
    /// </summary>
    /// <remarks>
    /// The settings entry is generated by the control rather than written in the page, so its font size cannot be
    /// set in XAML. Its icon and its row height need nothing here: both are theme resources the item template
    /// reads, and the page overrides them for every item at once.
    /// </remarks>
    private void ApplyNavigationItemSizing()
    {
        if (NavigationViewControl.SettingsItem is NavigationViewItem settingsItem &&
            Resources["ShellNavItemFontSize"] is double labelSize)
        {
            settingsItem.FontSize = labelSize;
        }
    }

    private void OnStartupShellStateChanged(object? sender, EventArgs e)
    {
        _ = DispatcherQueue.TryEnqueue(() =>
        {
            ApplyStartupShellState();
        });
    }

    private void ApplyStartupShellState()
    {
        NavigationViewControl.IsPaneVisible = _startupShellStateService.IsNavigationVisible;
        NavigationViewControl.IsSettingsVisible = _startupShellStateService.IsNavigationVisible;
    }

    private void ShellPage_Unloaded(object sender, RoutedEventArgs e)
    {
        NavigationFrame.Navigated -= NavigationFrame_Navigated;
        _startupShellStateService.StateChanged -= OnStartupShellStateChanged;
        Unloaded -= ShellPage_Unloaded;
    }

    private void NavigationFrame_Navigated(object sender, Microsoft.UI.Xaml.Navigation.NavigationEventArgs e)
    {
        SyncMyRequestsVisibility();
    }

    private void SyncMyRequestsVisibility()
    {
        if (NavigationFrame.GetPageViewModel() is WaitlistViewViewModel waitlistViewModel)
        {
            // The My Requests header filter applies only while the Waitlist (list) view is
            // active; keep its toggle in sync with the active view model's filter state.
            ViewModel.IsMyRequestsVisible = true;
            ViewModel.ShowMyRequestsOnly = waitlistViewModel.ShowMyRequestsOnly;

            // The sort control belongs to the list too, and the list has just resolved the order the viewer
            // remembers. Showing it here (rather than writing it) is what makes the control open on the order
            // that is actually in force (FR-011).
            ViewModel.SyncSortOrder(waitlistViewModel.SortOrder);
        }
        else
        {
            ViewModel.IsMyRequestsVisible = false;
            TitleBarSearchBox.Text = string.Empty;
            TitleBarSearchBox.ItemsSource = null;
        }
    }

    private void MyRequestsToggle_Toggled(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        if (NavigationFrame.GetPageViewModel() is WaitlistViewViewModel waitlistViewModel
            && sender is ToggleSwitch toggle)
        {
            waitlistViewModel.ShowMyRequestsOnly = toggle.IsOn;
        }
    }

    /// <summary>
    /// Rebuilds the facility flyout's cards as it opens, so the building in effect is never among them (FR-022).
    /// </summary>
    private void FacilityFlyout_Opening(object? sender, object e) => ViewModel.RefreshBuildingCards();

    /// <summary>Chooses the building whose card was clicked, which is the same choice the drop-down used to make.</summary>
    private void FacilityCard_Click(object sender, ItemClickEventArgs e)
    {
        if (e.ClickedItem is MTM_Waitlist.Module_Shared.Models.BuildingCardOption card)
        {
            ViewModel.SelectBuilding(card.Building);
        }
    }

    /// <summary>
    /// Marks the order the viewer is currently using. The options live in the shell's own header template, so
    /// their tick is set here when the menu opens rather than by a binding into that template.
    /// </summary>
    private void SortOrderFlyout_Opening(object? sender, object e)
    {
        if (sender is not MenuFlyout flyout)
        {
            return;
        }

        foreach (var item in flyout.Items.OfType<RadioMenuFlyoutItem>())
        {
            // The tag is the order key the option stands for; the service normalizes it, so an option whose tag
            // no longer names a key simply never shows as the current choice.
            item.IsChecked = string.Equals((string?)item.Tag, ViewModel.SelectedSortOrder, StringComparison.Ordinal);
        }
    }

    private void SortOrderItem_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        if (sender is not RadioMenuFlyoutItem item || item.Tag is not string sortOrder)
        {
            return;
        }

        ViewModel.ApplySortOrder(sortOrder);

        // Re-order the rows the viewer is looking at, without re-reading the store.
        if (NavigationFrame.GetPageViewModel() is WaitlistViewViewModel waitlistViewModel)
        {
            waitlistViewModel.ApplySortOrder(ViewModel.SelectedSortOrder);
        }
    }

    /// <summary>
    /// Signs out from the badge (FR-033, FR-034). The view model hands the work to the sign-out service, which
    /// clears the remembered credential and the local session, launches a replacement instance and exits this
    /// one — so a successful sign-out never comes back here. A relaunch that could not be performed is
    /// reported in plain language rather than leaving the person apparently signed in (FR-026).
    /// </summary>
    private async void SignOutItem_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        SignOutResult result;
        try
        {
            result = await ViewModel.SignOutAsync();
        }
        catch (Exception ex)
        {
            StartupDebugLog.Error("ShellPage", ex, "Signing out failed before the application could be relaunched.");
            result = SignOutResult.Refused(MTM_Waitlist.Module_Startup.Services.SignOutService.ResolveRestartFailedMessage());
        }

        if (result.Succeeded)
        {
            // The replacement instance is already running and this process is exiting.
            return;
        }

        // ShowAsync returns IAsyncOperation and must not be awaited through ConfigureAwait on this thread.
        var dialog = new ContentDialog
        {
            XamlRoot = XamlRoot,
            Title = "Shell_SignOut.Failed.Title".GetLocalized(),
            Content = result.Message,
            CloseButtonText = "Shell_SignOut.Close".GetLocalized(),
        };

        await dialog.ShowAsync();
    }

    private void TitleBarSearchBox_TextChanged(
        AutoSuggestBox sender,
        AutoSuggestBoxTextChangedEventArgs args)
    {
        if (args.Reason != AutoSuggestionBoxTextChangeReason.UserInput)
        {
            return;
        }

        if (NavigationFrame.GetPageViewModel() is not WaitlistViewViewModel viewModel)
        {
            sender.ItemsSource = null;
            return;
        }

        viewModel.UpdateSearchSuggestions(sender.Text);
        sender.ItemsSource = viewModel.SearchSuggestions;
    }

    private void TitleBarSearchBox_SuggestionChosen(
        AutoSuggestBox sender,
        AutoSuggestBoxSuggestionChosenEventArgs args)
    {
        if (args.SelectedItem is SampleOrder order)
        {
            sender.Text = order.Title;
        }
    }

    private void TitleBarSearchBox_QuerySubmitted(
        AutoSuggestBox sender,
        AutoSuggestBoxQuerySubmittedEventArgs args)
    {
        if (NavigationFrame.GetPageViewModel() is WaitlistViewViewModel viewModel)
        {
            viewModel.SubmitSearch(args.QueryText, args.ChosenSuggestion as SampleOrder);
        }
    }

    private void NavigationViewControl_DisplayModeChanged(NavigationView sender, NavigationViewDisplayModeChangedEventArgs args)
    {
        AppTitleBar.Margin = new Thickness()
        {
            Left = sender.CompactPaneLength * (sender.DisplayMode == NavigationViewDisplayMode.Minimal ? 2 : 1),
            Top = AppTitleBar.Margin.Top,
            Right = AppTitleBar.Margin.Right,
            Bottom = AppTitleBar.Margin.Bottom
        };
    }

    private static KeyboardAccelerator BuildKeyboardAccelerator(VirtualKey key, VirtualKeyModifiers? modifiers = null)
    {
        var keyboardAccelerator = new KeyboardAccelerator() { Key = key };

        if (modifiers.HasValue)
        {
            keyboardAccelerator.Modifiers = modifiers.Value;
        }

        keyboardAccelerator.Invoked += OnKeyboardAcceleratorInvoked;

        return keyboardAccelerator;
    }

    private static void OnKeyboardAcceleratorInvoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
    {
        var navigationService = App.GetService<INavigationService>();

        var result = navigationService.GoBack();

        args.Handled = result;
    }
}
