-- Stored Procedure: sp_auth_user_password_update
-- Engine: MySQL 5.7
-- Feature: 001-module-mock-visual-fallback (task T093)
--
-- Purpose: store a new password hash/salt for one active user and clear the forced-change flag. Replaces the
--          inline UPDATE in `StartupSessionRepository.UpdatePasswordAsync` (FR-015).
--
-- Contract:
--   IN  p_user_id        BIGINT
--   IN  p_password_hash  VARCHAR(128)     hex-encoded PBKDF2 hash (column width from core_users_profiles)
--   IN  p_password_salt  VARBINARY(32)    the per-user salt
--
--   OUT no result set. The affected-row count reaches the caller from the client (MySqlConnector's non-query
--       return value); 0 means the user was unknown or no longer active, which the caller reports as failure.
--
-- Semantics preserved exactly: the `is_active = 1` guard stays, `require_password_change` is cleared to 0 because
-- the change has just happened, and `updated_utc` is stamped from the server clock. The salt is regenerated by
-- the caller per change; the procedure never invents one, so an unset salt cannot slip through.
-- ============================================================

USE mtm_waitlist;

DROP PROCEDURE IF EXISTS sp_auth_user_password_update;

CREATE PROCEDURE sp_auth_user_password_update(
    IN p_user_id BIGINT,
    IN p_password_hash VARCHAR(128),
    IN p_password_salt VARBINARY(32)
)
UPDATE core_users_profiles
SET password_hash = p_password_hash,
    password_salt = p_password_salt,
    require_password_change = 0,
    updated_utc = UTC_TIMESTAMP()
WHERE id = p_user_id
  AND is_active = 1;
