-- Master stored-procedure list: mtm_mock
-- Engine: MySQL 5.7
--
-- GENERATED by Database/CopilotScripts/build_mtm_mock_masters.ps1 — do not edit by hand.
-- Source: Database/Mock/StoredProcedures/<name>/create.sql (concatenated verbatim, ordinal order).
--
-- Registered procedures: sp_visual_<shape>_{get,refresh}.

USE mtm_mock;

-- ============================================================
-- Artifact: sp_visual_disposition_input_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_disposition_input_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (read, shape 5 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T024)
-- Shape key:  disposition_input
-- ============================================================
--
-- Live projection: WorkOrderStatus, OpenWorkOrderQuantity, FinishedGoodsQuantity,
--                  HasOutsideVendorOperation   (the live read returns TOP (1)).
--
-- `WorkOrderStatus` is the raw Visual status code. Its MEANING is owned solely by
-- RequestDispositionStatusCodes (Open = {R,U,F}, Closed = {C}, X never FG); this read never
-- interprets it (FR-018).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_disposition_input_get;

CREATE PROCEDURE sp_visual_disposition_input_get(
    IN p_work_order VARCHAR(64),
    IN p_part_number VARCHAR(64)
)
SELECT
    work_order_status             AS WorkOrderStatus,
    open_work_order_quantity      AS OpenWorkOrderQuantity,
    finished_goods_quantity       AS FinishedGoodsQuantity,
    has_outside_vendor_operation  AS HasOutsideVendorOperation
FROM visual_disposition_input_result
WHERE work_order = p_work_order
  AND part_number = p_part_number
LIMIT 1;

-- ============================================================
-- Artifact: sp_visual_disposition_input_refresh
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_disposition_input_refresh
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (refresh, shape 5 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T019)
-- Shape key:  disposition_input
-- ============================================================
--
-- Follows the T015 reference pattern exactly. See that file for the full rationale.
--
--   p_rows : JSON array of result objects. Keys:
--              "WorkOrder", "PartNumber"      (the read's inputs)
--              "WorkOrderStatus", "OpenWorkOrderQuantity", "FinishedGoodsQuantity",
--              "HasOutsideVendorOperation"     (the read's outputs)
--
-- `WorkOrderStatus` is stored as the raw Visual status code. The status MEANING remains owned
-- solely by RequestDispositionStatusCodes; this cache never interprets it (FR-018).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_disposition_input_refresh;

DELIMITER $$

CREATE PROCEDURE sp_visual_disposition_input_refresh(
    IN p_rows JSON
)
BEGIN
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_loaded   INT DEFAULT 0;

    TRUNCATE TABLE visual_disposition_input_result_stage;

    SET v_expected = IFNULL(JSON_LENGTH(p_rows), 0);

    INSERT INTO visual_disposition_input_result_stage (
        work_order,
        part_number,
        work_order_status,
        open_work_order_quantity,
        finished_goods_quantity,
        has_outside_vendor_operation,
        refreshed_utc,
        is_seed_content
    )
    SELECT
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].WorkOrder'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].PartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].WorkOrderStatus'))),
        CAST(IFNULL(JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].OpenWorkOrderQuantity'))), '0') AS DECIMAL(18,4)),
        CAST(IFNULL(JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].FinishedGoodsQuantity'))), '0') AS DECIMAL(18,4)),
        CAST(IFNULL(JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].HasOutsideVendorOperation'))), '0') AS SIGNED),
        UTC_TIMESTAMP(),
        0
    FROM (
        SELECT (ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000) AS i
        FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS ones
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS tens
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS hundreds
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) AS thousands
    ) AS n
    WHERE n.i < v_expected;

    SELECT COUNT(*) INTO v_loaded FROM visual_disposition_input_result_stage;

    IF v_loaded <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'sp_visual_disposition_input_refresh: staged row count does not match payload length; live snapshot left untouched.';
    END IF;

    RENAME TABLE visual_disposition_input_result       TO visual_disposition_input_result_prev,
                 visual_disposition_input_result_stage TO visual_disposition_input_result,
                 visual_disposition_input_result_prev  TO visual_disposition_input_result_stage;
END $$

DELIMITER ;

-- ============================================================
-- Artifact: sp_visual_inventory_locations_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_inventory_locations_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (read, shape 4 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T023)
-- Shape key:  inventory_locations
-- ============================================================
--
-- Live projection: PartNumber, Location, OnHandQuantity  (ORDER BY Location, part.ID).
--
-- The caller-side on-hand >= 1 filter and ignored-location filtering stay in the caller and are
-- deliberately NOT applied here (data-model.md §3.4) — the mirror returns the same rows the live
-- read would, and the caller filters identically whichever source answered.
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_inventory_locations_get;

CREATE PROCEDURE sp_visual_inventory_locations_get(
    IN p_part_number VARCHAR(64)
)
SELECT
    part_number       AS PartNumber,
    location          AS Location,
    on_hand_quantity  AS OnHandQuantity
FROM visual_inventory_locations_result
WHERE part_number = p_part_number
ORDER BY location, part_number;

-- ============================================================
-- Artifact: sp_visual_inventory_locations_refresh
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_inventory_locations_refresh
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (refresh, shape 4 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T018)
-- Shape key:  inventory_locations
-- ============================================================
--
-- Follows the T015 reference pattern exactly. See that file for the full rationale.
--
--   p_rows : JSON array of result objects. Keys:
--              "PartNumber"        (the read's input AND its returned part number)
--              "Location", "OnHandQuantity"   (the read's outputs)
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_inventory_locations_refresh;

DELIMITER $$

CREATE PROCEDURE sp_visual_inventory_locations_refresh(
    IN p_rows JSON
)
BEGIN
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_loaded   INT DEFAULT 0;

    TRUNCATE TABLE visual_inventory_locations_result_stage;

    SET v_expected = IFNULL(JSON_LENGTH(p_rows), 0);

    INSERT INTO visual_inventory_locations_result_stage (
        part_number,
        location,
        on_hand_quantity,
        refreshed_utc,
        is_seed_content
    )
    SELECT
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].PartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Location'))),
        CAST(JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].OnHandQuantity'))) AS DECIMAL(18,4)),
        UTC_TIMESTAMP(),
        0
    FROM (
        SELECT (ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000) AS i
        FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS ones
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS tens
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS hundreds
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) AS thousands
    ) AS n
    WHERE n.i < v_expected;

    SELECT COUNT(*) INTO v_loaded FROM visual_inventory_locations_result_stage;

    IF v_loaded <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'sp_visual_inventory_locations_refresh: staged row count does not match payload length; live snapshot left untouched.';
    END IF;

    RENAME TABLE visual_inventory_locations_result       TO visual_inventory_locations_result_prev,
                 visual_inventory_locations_result_stage TO visual_inventory_locations_result,
                 visual_inventory_locations_result_prev  TO visual_inventory_locations_result_stage;
END $$

DELIMITER ;

-- ============================================================
-- Artifact: sp_visual_operation_sequences_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_operation_sequences_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (read, shape 2 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T021)
-- Shape key:  operation_sequences
-- ============================================================
--
-- Live projection: SequenceNumber, Description  (ORDER BY o.SEQUENCE_NO).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_operation_sequences_get;

CREATE PROCEDURE sp_visual_operation_sequences_get(
    IN p_normalized_work_order VARCHAR(64),
    IN p_part_number VARCHAR(64)
)
SELECT
    sequence_number AS SequenceNumber,
    description     AS Description
FROM visual_operation_sequences_result
WHERE normalized_work_order = p_normalized_work_order
  AND part_number = p_part_number
ORDER BY sequence_number;

-- ============================================================
-- Artifact: sp_visual_operation_sequences_refresh
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_operation_sequences_refresh
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (refresh, shape 2 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T016)
-- Shape key:  operation_sequences
-- ============================================================
--
-- Follows the T015 reference pattern exactly (see sp_visual_work_order_lookup_refresh/create.sql
-- for the full rationale): truncate stage → load complete payload → validate → atomic 3-name swap.
--
--   p_rows : JSON array of result objects. Keys:
--              "NormalizedWorkOrder", "PartNumber"      (the read's input keys)
--              "SequenceNumber", "Description"          (the read's outputs)
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_operation_sequences_refresh;

DELIMITER $$

CREATE PROCEDURE sp_visual_operation_sequences_refresh(
    IN p_rows JSON
)
BEGIN
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_loaded   INT DEFAULT 0;

    TRUNCATE TABLE visual_operation_sequences_result_stage;

    SET v_expected = IFNULL(JSON_LENGTH(p_rows), 0);

    INSERT INTO visual_operation_sequences_result_stage (
        normalized_work_order,
        part_number,
        sequence_number,
        description,
        refreshed_utc,
        is_seed_content
    )
    SELECT
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].NormalizedWorkOrder'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].PartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].SequenceNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Description'))),
        UTC_TIMESTAMP(),
        0
    FROM (
        SELECT (ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000) AS i
        FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS ones
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS tens
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS hundreds
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) AS thousands
    ) AS n
    WHERE n.i < v_expected;

    SELECT COUNT(*) INTO v_loaded FROM visual_operation_sequences_result_stage;

    IF v_loaded <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'sp_visual_operation_sequences_refresh: staged row count does not match payload length; live snapshot left untouched.';
    END IF;

    RENAME TABLE visual_operation_sequences_result       TO visual_operation_sequences_result_prev,
                 visual_operation_sequences_result_stage TO visual_operation_sequences_result,
                 visual_operation_sequences_result_prev  TO visual_operation_sequences_result_stage;
END $$

DELIMITER ;

-- ============================================================
-- Artifact: sp_visual_read_shape_metadata_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_read_shape_metadata_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (metadata)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T109)
-- ============================================================
--
-- Purpose
-- -------
-- Reports, for a requested read shape (or for every shape present), whether that shape's
-- artifacts actually exist in `mtm_mock`, plus the mirror table's ACTUAL column list taken
-- from information_schema.
--
-- This exists so the service's shape-catalog startup validation (RefreshShapeCatalogProvider,
-- tasks T029/T086/T110) can check catalog-to-artifact agreement WITHOUT hand-writing schema
-- queries in C#. Constitution III forbids inline/hard-coded SQL statement text in application
-- code, and task T098's inline-SQL audit would otherwise need an exemption for metadata reads.
-- Routing the check through this procedure keeps the SP-first rule intact with no exemption.
--
-- Contract (data-model.md §12)
-- ---------------------------
--   IN  p_shape_key  VARCHAR(64)
--         A shape key such as 'work_order_lookup'.
--         NULL => report every shape whose mirror table exists.
--         Non-NULL => always report that shape, even when none of its artifacts exist
--                     (so a half-added shape is reported rather than silently absent).
--
--   OUT (one row per shape)
--     shape_key                 the requested/derived shape key
--     mirror_table_exists       1 when visual_<key>_result exists
--     stage_table_exists        1 when visual_<key>_result_stage exists
--     get_procedure_exists      1 when sp_visual_<key>_get exists
--     refresh_procedure_exists  1 when sp_visual_<key>_refresh exists
--     mirror_columns            comma-joined actual column names (NULL when the table is absent)
--
-- Notes
-- -----
-- `mirror_columns` lists PHYSICAL columns, so it includes the metadata columns `id`,
-- `refreshed_utc`, and `is_seed_content`. The catalog provider compares only the projection
-- columns when validating `outputColumns` (see RefreshShapeCatalogProvider).
--
-- The derived key is computed as SUBSTRING(table_name, 8, LENGTH - 14): `visual_` is 7
-- characters and `_result` is 7, so the middle is the shape key verbatim.
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_read_shape_metadata_get;

CREATE PROCEDURE sp_visual_read_shape_metadata_get(
    IN p_shape_key VARCHAR(64)
)
SELECT
    k.shape_key,
    (SELECT COUNT(*)
       FROM information_schema.tables tb
      WHERE tb.table_schema = DATABASE()
        AND tb.table_name = CONCAT('visual_', k.shape_key, '_result')) AS mirror_table_exists,
    (SELECT COUNT(*)
       FROM information_schema.tables tb
      WHERE tb.table_schema = DATABASE()
        AND tb.table_name = CONCAT('visual_', k.shape_key, '_result_stage')) AS stage_table_exists,
    (SELECT COUNT(*)
       FROM information_schema.routines r
      WHERE r.routine_schema = DATABASE()
        AND r.routine_name = CONCAT('sp_visual_', k.shape_key, '_get')) AS get_procedure_exists,
    (SELECT COUNT(*)
       FROM information_schema.routines r
      WHERE r.routine_schema = DATABASE()
        AND r.routine_name = CONCAT('sp_visual_', k.shape_key, '_refresh')) AS refresh_procedure_exists,
    (SELECT GROUP_CONCAT(c.column_name ORDER BY c.ordinal_position)
       FROM information_schema.columns c
      WHERE c.table_schema = DATABASE()
        AND c.table_name = CONCAT('visual_', k.shape_key, '_result')) AS mirror_columns
FROM (
    SELECT DISTINCT SUBSTRING(tb.table_name, 8, CHAR_LENGTH(tb.table_name) - 14) AS shape_key
      FROM information_schema.tables tb
     WHERE tb.table_schema = DATABASE()
       AND tb.table_name LIKE 'visual\_%\_result'
    UNION
    SELECT p_shape_key FROM DUAL
) AS k
WHERE k.shape_key IS NOT NULL
  AND (p_shape_key IS NULL OR k.shape_key = p_shape_key)
ORDER BY k.shape_key;

-- ============================================================
-- Artifact: sp_visual_subordinate_parts_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_subordinate_parts_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (read, shape 3 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T022)
-- Shape key:  subordinate_parts
-- ============================================================
--
-- Live projection: Category, PartNumber, Description, Location, User8, OnHandQuantity
-- (ORDER BY Category, req.PART_ID).
--
-- The live read takes the OPERATION's part number as an input. That input is persisted as
-- `parent_part_number`, and the procedure exposes it as `p_part_number` so callers see the same
-- parameter name and meaning as the live read (data-model.md §3.3). `PartNumber` in the RETURNED
-- rows is always the subordinate part.
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_subordinate_parts_get;

CREATE PROCEDURE sp_visual_subordinate_parts_get(
    IN p_normalized_work_order VARCHAR(64),
    IN p_part_number VARCHAR(64),
    IN p_sequence_number INT
)
SELECT
    category          AS Category,
    part_number       AS PartNumber,
    description       AS Description,
    location          AS Location,
    user8             AS User8,
    on_hand_quantity  AS OnHandQuantity
FROM visual_subordinate_parts_result
WHERE normalized_work_order = p_normalized_work_order
  AND parent_part_number = p_part_number
  AND sequence_number = p_sequence_number
ORDER BY category, part_number;

-- ============================================================
-- Artifact: sp_visual_subordinate_parts_refresh
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_subordinate_parts_refresh
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (refresh, shape 3 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T017)
-- Shape key:  subordinate_parts
-- ============================================================
--
-- Follows the T015 reference pattern exactly. See that file for the full rationale.
--
--   p_rows : JSON array of result objects. Keys:
--              "NormalizedWorkOrder", "ParentPartNumber", "SequenceNumber"  (the read's inputs)
--              "Category", "PartNumber", "Description", "Location", "User8",
--              "OnHandQuantity"                                             (the read's outputs)
--
-- KEY NAMING: the live read's input part number and its returned subordinate part number are both
-- called `PartNumber` in the Visual source. The payload therefore uses `ParentPartNumber` for the
-- INPUT (persisted as `parent_part_number`) so that `PartNumber` in a payload object means exactly
-- what it means in the live result (data-model.md §3.3).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_subordinate_parts_refresh;

DELIMITER $$

CREATE PROCEDURE sp_visual_subordinate_parts_refresh(
    IN p_rows JSON
)
BEGIN
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_loaded   INT DEFAULT 0;

    TRUNCATE TABLE visual_subordinate_parts_result_stage;

    SET v_expected = IFNULL(JSON_LENGTH(p_rows), 0);

    INSERT INTO visual_subordinate_parts_result_stage (
        normalized_work_order,
        parent_part_number,
        sequence_number,
        category,
        part_number,
        description,
        location,
        user8,
        on_hand_quantity,
        refreshed_utc,
        is_seed_content
    )
    SELECT
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].NormalizedWorkOrder'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].ParentPartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].SequenceNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Category'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].PartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Description'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Location'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].User8'))),
        CAST(JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].OnHandQuantity'))) AS DECIMAL(18,4)),
        UTC_TIMESTAMP(),
        0
    FROM (
        SELECT (ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000) AS i
        FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS ones
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS tens
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS hundreds
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) AS thousands
    ) AS n
    WHERE n.i < v_expected;

    SELECT COUNT(*) INTO v_loaded FROM visual_subordinate_parts_result_stage;

    IF v_loaded <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'sp_visual_subordinate_parts_refresh: staged row count does not match payload length; live snapshot left untouched.';
    END IF;

    RENAME TABLE visual_subordinate_parts_result       TO visual_subordinate_parts_result_prev,
                 visual_subordinate_parts_result_stage TO visual_subordinate_parts_result,
                 visual_subordinate_parts_result_prev  TO visual_subordinate_parts_result_stage;
END $$

DELIMITER ;

-- ============================================================
-- Artifact: sp_visual_work_order_lookup_get
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_work_order_lookup_get
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (read, shape 1 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T020)
-- Shape key:  work_order_lookup
-- ============================================================
--
-- Parameterized read of the LIVE mirror. Returns exactly the column shape the live Infor Visual
-- read returns (FR-004), so a caller cannot distinguish cached from live:
--   live : PartNumber, Description, WorkCenter   (ORDER BY wo.PART_ID)
--   here : same names/order, projected from the mirror's own columns.
--
-- Before the first successful refresh the mirror holds baseline seed rows (is_seed_content = 1),
-- so a fresh install returns a usable result rather than an error (FR-017).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_work_order_lookup_get;

CREATE PROCEDURE sp_visual_work_order_lookup_get(
    IN p_normalized_work_order VARCHAR(64)
)
SELECT
    part_number  AS PartNumber,
    description  AS Description,
    work_center  AS WorkCenter
FROM visual_work_order_lookup_result
WHERE normalized_work_order = p_normalized_work_order
ORDER BY part_number;

-- ============================================================
-- Artifact: sp_visual_work_order_lookup_refresh
-- ============================================================

-- ============================================================
-- Stored Procedure: sp_visual_work_order_lookup_refresh
-- Database:   mtm_mock
-- Engine:     MySQL 5.7 (verified on 9.6)
-- Kind:       StoredProcedure / create  (reference refresh pattern, shape 1 of 5)
-- Created:    2026-09-09
-- Feature:    001-module-mock-visual-fallback (task T015)
-- Shape key:  work_order_lookup
-- ============================================================
--
-- Purpose
-- -------
-- Replace the live mirror `visual_work_order_lookup_result` with a complete new result set,
-- atomically. Readers address only the live table name, so they always observe either the
-- complete previous snapshot or the complete new one — never a partial set and never an empty
-- table (FR-006, SC-005). See research.md R1 and data-model.md §3.6.
--
-- Contract (design A — confirmed 2026-09-09)
-- ------------------------------------------
-- The Infor Visual read is external (SQL Server) and the caller owns the driver inputs, so the
-- SERVICE produces the complete result and hands it to this procedure. The procedure owns the
-- swap so the atomic multi-table RENAME stays in the database (constitution III, SP-first).
-- The service cannot INSERT the stage rows itself: C# may not contain MySQL statement text
-- (inline-SQL audit, task T098).
--
--   p_rows : JSON array of result objects. Keys are the live read's projection names:
--              "NormalizedWorkOrder" (the read's input key)
--              "PartNumber", "Description", "WorkCenter"
--            A NULL or empty array produces an empty snapshot, which is a legitimate result
--            (an empty live read is a valid answer — FR-024).
--
-- Steps
-- -----
--   1. TRUNCATE the stage twin.
--   2. Expand p_rows into the stage twin (refreshed_utc = UTC_TIMESTAMP(), is_seed_content = 0).
--   3. Validate: the loaded row count must equal JSON_LENGTH(p_rows); otherwise SIGNAL and abort.
--   4. Atomic swap in ONE statement (documented left-to-right three-name idiom; the middle step's
--      target name is temporarily occupied by the outgoing snapshot):
--          result -> result_prev, result_stage -> result, result_prev -> result_stage
--      The transient `_prev` name never persists between cycles.
--
-- Failure behaviour (FR-006)
-- --------------------------
-- Any error before step 4 (bad payload, NOT NULL violation, validation mismatch) aborts the
-- procedure with the live table UNTOUCHED. A partially loaded stage twin is discarded by the
-- TRUNCATE at the start of the next cycle. MySQL documents RENAME TABLE as all-or-nothing:
-- "If any errors occur during a RENAME TABLE, the statement fails and no changes are made."
--
-- Row cap
-- -------
-- The inline tally covers 0..1999 rows, which bounds the JSON expansion without a helper table
-- (data-model.md §11: mtm_mock carries no table other than the mirrors and their stage twins).
-- ============================================================

USE mtm_mock;

DROP PROCEDURE IF EXISTS sp_visual_work_order_lookup_refresh;

DELIMITER $$

CREATE PROCEDURE sp_visual_work_order_lookup_refresh(
    IN p_rows JSON
)
BEGIN
    DECLARE v_expected INT DEFAULT 0;
    DECLARE v_loaded   INT DEFAULT 0;

    -- 1. Clear the stage twin (also discards any partially loaded previous attempt).
    TRUNCATE TABLE visual_work_order_lookup_result_stage;

    -- 2. Load the complete new result set into the stage twin.
    SET v_expected = IFNULL(JSON_LENGTH(p_rows), 0);

    INSERT INTO visual_work_order_lookup_result_stage (
        normalized_work_order,
        part_number,
        description,
        work_center,
        refreshed_utc,
        is_seed_content
    )
    SELECT
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].NormalizedWorkOrder'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].PartNumber'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].Description'))),
        JSON_UNQUOTE(JSON_EXTRACT(p_rows, CONCAT('$[', n.i, '].WorkCenter'))),
        UTC_TIMESTAMP(),
        0
    FROM (
        SELECT (ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000) AS i
        FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS ones
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS tens
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS hundreds
        CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) AS thousands
    ) AS n
    WHERE n.i < v_expected;

    -- 3. Validate the load before it can become visible.
    SELECT COUNT(*) INTO v_loaded FROM visual_work_order_lookup_result_stage;

    IF v_loaded <> v_expected THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'sp_visual_work_order_lookup_refresh: staged row count does not match payload length; live snapshot left untouched.';
    END IF;

    -- 4. Atomic swap — the live name always resolves to a complete snapshot.
    RENAME TABLE visual_work_order_lookup_result       TO visual_work_order_lookup_result_prev,
                 visual_work_order_lookup_result_stage TO visual_work_order_lookup_result,
                 visual_work_order_lookup_result_prev  TO visual_work_order_lookup_result_stage;
END $$

DELIMITER ;
