-- Master table list: mtm_mock
-- Engine: MySQL 5.7
--
-- GENERATED by Database/CopilotScripts/build_mtm_mock_masters.ps1 â€” do not edit by hand.
-- Source: Database/Mock/Tables/<name>/create.sql (concatenated verbatim, ordinal order).
--
-- Registered tables: five mirrors + their stage twins.

USE mtm_mock;

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- Artifact: visual_disposition_input_result
-- ============================================================

-- ============================================================
-- Object:      visual_disposition_input_result
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (mirror, shape 5 of 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T013)
-- Shape key:   disposition_input
-- Source read: Database/InforVisual/Queues/Module_Waitlist/Queries/GetDispositionInput.sql
-- Caller:      RequestDispositionResolver.GetDispositionInputAsync
-- ============================================================
--
-- See visual_work_order_lookup_result/create.sql for the shared mirror-table rationale and
-- the approved R9 `work_order` naming deviation (this table carries the same banned word).
--
-- `work_order_status` remains a raw Visual status code (C/R/U/F/X). The status MEANING is
-- owned solely by RequestDispositionStatusCodes (Open = {R,U,F}, Closed = {C}, X never FG) â€”
-- this cache never interprets it (data-model.md Â§3.5, FR-018).
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_disposition_input_result (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    work_order_status VARCHAR(8) NULL,
    open_work_order_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    finished_goods_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    has_outside_vendor_operation TINYINT(1) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_disposition_input_result_lookup_key (work_order, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_disposition_input_result_stage
-- ============================================================

-- ============================================================
-- Object:      visual_disposition_input_result_stage
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (stage twin of shape 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T013)
-- ============================================================
--
-- Identical-structure staging twin; see visual_work_order_lookup_result_stage/create.sql.
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_disposition_input_result_stage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    work_order_status VARCHAR(8) NULL,
    open_work_order_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    finished_goods_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    has_outside_vendor_operation TINYINT(1) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_disposition_input_result_lookup_key (work_order, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_inventory_locations_result
-- ============================================================

-- ============================================================
-- Object:      visual_inventory_locations_result
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (mirror, shape 4 of 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T012)
-- Shape key:   inventory_locations
-- Source read: Database/InforVisual/Queues/Module_Waitlist/Queries/GetInventoryLocations.sql
-- Caller:      WaitlistInventoryService.GetInventoryLocationsFromBackendAsync
-- ============================================================
--
-- See visual_work_order_lookup_result/create.sql for the shared mirror-table rationale.
--
-- `part_number` is BOTH the read's input parameter and one of its output columns (the live
-- read returns the part number it was given), so a single column serves both roles.
-- The caller-side on-hand >= 1 filter and ignored-location filtering are unchanged and are
-- NOT applied here (data-model.md Â§3.4).
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_inventory_locations_result (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    part_number VARCHAR(64) NOT NULL,
    location VARCHAR(64) NOT NULL,
    on_hand_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_inventory_locations_result_location (part_number, location)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_inventory_locations_result_stage
-- ============================================================

-- ============================================================
-- Object:      visual_inventory_locations_result_stage
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (stage twin of shape 4)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T012)
-- ============================================================
--
-- Identical-structure staging twin; see visual_work_order_lookup_result_stage/create.sql.
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_inventory_locations_result_stage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    part_number VARCHAR(64) NOT NULL,
    location VARCHAR(64) NOT NULL,
    on_hand_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_inventory_locations_result_location (part_number, location)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_operation_sequences_result
-- ============================================================

-- ============================================================
-- Object:      visual_operation_sequences_result
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (mirror, shape 2 of 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T010)
-- Shape key:   operation_sequences
-- Source read: Database/InforVisual/Queues/Module_Setup/Queries/GetSequences.sql
-- Caller:      SetupLookupService.GetSequencesFromBackendAsync
-- ============================================================
--
-- See visual_work_order_lookup_result/create.sql for the shared mirror-table rationale and
-- the approved R9 `work_order` naming deviation.
--
-- `sequence_number` is typed INT UNSIGNED because the Visual source sequence is numeric
-- (OPERATION.SEQUENCE_NO). A real-data type mismatch is a FAILED refresh that leaves the
-- live snapshot untouched â€” never a corrupted snapshot (data-model.md Â§3.2, FR-006).
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_operation_sequences_result (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    sequence_number INT UNSIGNED NOT NULL,
    description VARCHAR(255) NULL,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_operation_sequences_result_lookup_key
        (normalized_work_order, part_number, sequence_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_operation_sequences_result_stage
-- ============================================================

-- ============================================================
-- Object:      visual_operation_sequences_result_stage
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (stage twin of shape 2)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T010)
-- ============================================================
--
-- Identical-structure staging twin; see visual_work_order_lookup_result_stage/create.sql.
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_operation_sequences_result_stage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    sequence_number INT UNSIGNED NOT NULL,
    description VARCHAR(255) NULL,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_operation_sequences_result_lookup_key
        (normalized_work_order, part_number, sequence_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_subordinate_parts_result
-- ============================================================

-- ============================================================
-- Object:      visual_subordinate_parts_result
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (mirror, shape 3 of 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T011)
-- Shape key:   subordinate_parts
-- Source read: Database/InforVisual/Queues/Module_Setup/Queries/GetSubordinateParts.sql
-- Caller:      SetupLookupService.GetSubordinatePartsFromBackendAsync
-- ============================================================
--
-- See visual_work_order_lookup_result/create.sql for the shared mirror-table rationale and
-- the approved R9 `work_order` naming deviation.
--
-- COLUMN RENAME (data-model.md Â§3.3): the live read takes the OPERATION's part number as an
-- input AND returns each SUBORDINATE part's number as an output â€” both are `PartNumber` in
-- the source. The input key is persisted as `parent_part_number` so that `part_number` in a
-- returned row means exactly what it means in the live result. sp_visual_subordinate_parts_get
-- exposes the input as `p_part_number`, so callers see no difference (FR-004).
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_subordinate_parts_result (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    parent_part_number VARCHAR(64) NOT NULL,
    sequence_number INT UNSIGNED NOT NULL,
    category VARCHAR(64) NULL,
    part_number VARCHAR(64) NOT NULL,
    description VARCHAR(255) NULL,
    location VARCHAR(64) NULL,
    user8 VARCHAR(64) NULL,
    on_hand_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_subordinate_parts_result_lookup_key
        (normalized_work_order, parent_part_number, sequence_number, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_subordinate_parts_result_stage
-- ============================================================

-- ============================================================
-- Object:      visual_subordinate_parts_result_stage
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (stage twin of shape 3)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T011)
-- ============================================================
--
-- Identical-structure staging twin; see visual_work_order_lookup_result_stage/create.sql.
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_subordinate_parts_result_stage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    parent_part_number VARCHAR(64) NOT NULL,
    sequence_number INT UNSIGNED NOT NULL,
    category VARCHAR(64) NULL,
    part_number VARCHAR(64) NOT NULL,
    description VARCHAR(255) NULL,
    location VARCHAR(64) NULL,
    user8 VARCHAR(64) NULL,
    on_hand_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_subordinate_parts_result_lookup_key
        (normalized_work_order, parent_part_number, sequence_number, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_work_order_lookup_result
-- ============================================================

-- ============================================================
-- Object:      visual_work_order_lookup_result
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (mirror, shape 1 of 5)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T009)
-- Shape key:   work_order_lookup
-- Source read: Database/InforVisual/Queues/Module_Setup/Queries/LookupWorkOrder.sql
-- Caller:      SetupLookupService.LookupWorkOrderFromBackendAsync
-- ============================================================
--
-- Stores the flattened result of the Infor Visual work-order lookup read so the app can
-- serve a complete, identically shaped result while Infor Visual is unreachable
-- (FR-002, FR-004). Read exactly once from a snapshot: the live table always resolves to a
-- complete result because refreshes swap it atomically with its _stage twin (FR-006).
--
-- DDL-REVIEW DEVIATION (R9) â€” approved by the Tech Lead (database reviewer) at the
-- Phase 1 DDL review:
--   The locked DB ruleset (Database/Database-Ruleset.md) lists `work_order` as a banned
--   word. The shape key and the mirrored business entity are `work_order` by deliberate
--   decision (matching the frozen shape catalog in data-model.md Â§3.1 and the existing
--   `22_mock_work_orders` precedent). The deviation is surfaced here rather than silently
--   diverging. Cross-reference: research.md R9, data-model.md Â§3.1.
--
-- Banned-word note also applies to `visual_disposition_input_result.work_order` (shape 5).
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_work_order_lookup_result (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    description VARCHAR(255) NULL,
    work_center VARCHAR(32) NULL,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_work_order_lookup_result_work_order (normalized_work_order, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ============================================================
-- Artifact: visual_work_order_lookup_result_stage
-- ============================================================

-- ============================================================
-- Object:      visual_work_order_lookup_result_stage
-- Database:    mtm_mock
-- Engine:      MySQL 5.7
-- Kind:        Table / create (stage twin of shape 1)
-- Created:     2026-09-09
-- Feature:     001-module-mock-visual-fallback (task T009)
-- ============================================================
--
-- Identical-structure staging twin. Written ONLY by sp_visual_work_order_lookup_refresh and
-- never read by the application. The refresh procedure truncates it, loads the complete new
-- result, then performs an atomic multi-table RENAME TABLE swap with the live mirror.
--
-- The index name is intentionally identical to the live mirror's so the swap does not change
-- the live table's key names (the unique key travels with the table).
-- See data-model.md Â§3.6.
-- ============================================================

USE mtm_mock;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS visual_work_order_lookup_result_stage (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    normalized_work_order VARCHAR(64) NOT NULL,
    part_number VARCHAR(64) NOT NULL,
    description VARCHAR(255) NULL,
    work_center VARCHAR(32) NULL,
    refreshed_utc DATETIME NOT NULL,
    is_seed_content TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visual_work_order_lookup_result_work_order (normalized_work_order, part_number)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
