-- Stored Procedure: sp_auth_remembered_sign_ins_upsert
-- Engine: MySQL 5.7
-- Feature: 010-startup-rebuild (task T046)
--
-- Purpose: store or replace the remembered sign-in for a person on this machine (FR-014).
--
-- Contract:
--   IN  p_public_id          CHAR(36)      generated by the caller, which reads the row back by it
--   IN  p_user_id            BIGINT
--   IN  p_computer_id        BIGINT
--   IN  p_payload_ciphertext VARBINARY(512) the encrypted payload; opaque here
--   IN  p_payload_iv         VARBINARY(16)  the initialisation vector it was produced with
--   IN  p_key_fingerprint    CHAR(64)       identifies the key that encrypted it
--   OUT the affected-row count, through the non-query seam. This is a write and returns no result set.
--
-- One row per person per machine, as the table's key requires: re-remembering replaces the payload, the vector
-- and the fingerprint in place and reactivates a row that had been cleared. `created_utc` is left alone on the
-- replace path for the same reason the session writer leaves it alone — it records the first time, not the
-- most recent.
--
-- Nothing here validates the ciphertext, and nothing can: the store has no key and no plaintext. Its only
-- obligations are to keep the three parts together and to keep them out of every log and every error message.

USE mtm_waitlist;

DROP PROCEDURE IF EXISTS sp_auth_remembered_sign_ins_upsert;

DELIMITER $$

CREATE PROCEDURE sp_auth_remembered_sign_ins_upsert(
    IN p_public_id CHAR(36),
    IN p_user_id BIGINT,
    IN p_computer_id BIGINT,
    IN p_payload_ciphertext VARBINARY(512),
    IN p_payload_iv VARBINARY(16),
    IN p_key_fingerprint CHAR(64)
)
BEGIN
    DECLARE v_now_utc DATETIME;

    SET v_now_utc = fn_server_utc_now();

    INSERT INTO auth_remembered_sign_ins (
        public_id,
        user_id,
        computer_id,
        payload_ciphertext,
        payload_iv,
        key_fingerprint,
        is_active,
        created_utc,
        updated_utc
    )
    VALUES (
        TRIM(p_public_id),
        p_user_id,
        p_computer_id,
        p_payload_ciphertext,
        p_payload_iv,
        LOWER(TRIM(p_key_fingerprint)),
        1,
        v_now_utc,
        v_now_utc
    )
    ON DUPLICATE KEY UPDATE
        public_id = VALUES(public_id),
        payload_ciphertext = VALUES(payload_ciphertext),
        payload_iv = VALUES(payload_iv),
        key_fingerprint = VALUES(key_fingerprint),
        is_active = 1,
        updated_utc = v_now_utc;
END$$

DELIMITER ;
