-- Stored Procedure: sp_config_images_locations_insert
-- Engine: MySQL 5.7
-- Feature: 001-module-mock-visual-fallback (task T094)
--
-- Purpose: create one image override. Replaces the inline INSERT in
--          `ImageOverrideWriteService.CreateOverrideAsync` (FR-015).
--
-- Contract:
--   IN  p_public_id      CHAR(36)      generated by the caller, which reads the row back by this value
--   IN  p_scope          VARCHAR(16)
--   IN  p_scope_item_id  VARCHAR(190)
--   IN  p_image_path     VARCHAR(500)
--   IN  p_user_id        BIGINT        NULL when the caller has no user
--   OUT affected row count (0 or 1); the caller treats anything but 1 as a database error, and MySQL's duplicate
--       key error for `uq_config_images_locations_scope_item` still surfaces as exception number 1062.
--
-- Field values the caller does not choose are generated here, matching the statement this replaces:
-- `is_active` is 1 because this is the create path, and both timestamps are `UTC_TIMESTAMP()` so the pair cannot
-- disagree. Both `*_by_user_id` columns take the same parameter — create and update are the same actor.
--
-- Parameter widths are the live column widths, so an over-long value fails here rather than being silently
-- truncated by the server.
-- ============================================================

USE mtm_waitlist;

DROP PROCEDURE IF EXISTS sp_config_images_locations_insert;

CREATE PROCEDURE sp_config_images_locations_insert(
    IN p_public_id CHAR(36),
    IN p_scope VARCHAR(16),
    IN p_scope_item_id VARCHAR(190),
    IN p_image_path VARCHAR(500),
    IN p_user_id BIGINT
)
INSERT INTO config_images_locations (
    public_id,
    scope,
    scope_item_id,
    image_path,
    is_active,
    created_by_user_id,
    updated_by_user_id,
    created_utc,
    updated_utc
)
VALUES (
    p_public_id,
    p_scope,
    p_scope_item_id,
    p_image_path,
    1,
    p_user_id,
    p_user_id,
    UTC_TIMESTAMP(),
    UTC_TIMESTAMP()
);
