-- Stored Procedure: sp_auth_user_active_sessions_upsert
-- Engine: MySQL 5.7
-- Feature: 010-startup-rebuild (task T045)
--
-- Purpose: write or replace the one active session for a person on this machine (FR-010).
--
-- Contract:
--   IN  p_public_id               CHAR(36)     generated by the caller, which reads the row back by it
--   IN  p_user_id                 BIGINT
--   IN  p_computer_id             BIGINT
--   IN  p_token_hash              CHAR(64)     the caller's SHA-256 hex digest; the token itself never arrives
--   IN  p_token_salt              VARBINARY(32) the salt that digest was computed with
--   IN  p_session_length_minutes  INT          read from the session-length setting at sign-in time
--   IN  p_source_label            VARCHAR(32)  the caller's vocabulary for where the session came from
--   OUT the affected-row count, through the non-query seam. This is a write and returns no result set, so the
--       caller that needs `expires_utc` reads it back through sp_auth_user_active_sessions_get. MySQL reports
--       1 for an insert and 2 for a replace, so the caller treats "less than 1" as the failure, exactly as the
--       other writes in this repository do.
--
-- `expires_utc` is computed here rather than supplied, because "now" has to be the store's clock: the
-- workstation's clock is never consulted for session validity (ruleset, "Session and Security"). Both
-- `issued_utc` and `expires_utc` come from that one reading of `fn_server_utc_now()`, so a session can never be
-- issued after it expires.
--
-- The replace path is what makes "one active row per person per machine" true rather than merely intended: a
-- second sign-in on the same machine repoints the existing row at the new digest and clears the revocation in
-- the same statement, so there is no instant at which the machine holds two sessions for one person.
--
-- A session length that is missing or not positive is refused as `mtm_session_length_invalid` rather than
-- silently becoming "never expires", because a session with no lifetime is the one outcome the requirement
-- does not allow.
-- ============================================================

USE mtm_waitlist;

DROP PROCEDURE IF EXISTS sp_auth_user_active_sessions_upsert;

-- DELIMITER because this body is compound; see the note in
-- sp_auth_temporary_credential_attempt_record/create.sql.
DELIMITER $$

CREATE PROCEDURE sp_auth_user_active_sessions_upsert(
    IN p_public_id CHAR(36),
    IN p_user_id BIGINT,
    IN p_computer_id BIGINT,
    IN p_token_hash CHAR(64),
    IN p_token_salt VARBINARY(32),
    IN p_session_length_minutes INT,
    IN p_source_label VARCHAR(32)
)
BEGIN
    DECLARE v_now_utc DATETIME;
    DECLARE v_expires_utc DATETIME;

    IF p_session_length_minutes IS NULL OR p_session_length_minutes <= 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'mtm_session_length_invalid';
    END IF;

    SET v_now_utc = fn_server_utc_now();
    SET v_expires_utc = DATE_ADD(v_now_utc, INTERVAL p_session_length_minutes MINUTE);

    INSERT INTO user_active_sessions (
        public_id,
        user_id,
        computer_id,
        token_hash,
        token_salt,
        issued_utc,
        expires_utc,
        revoked_utc,
        is_active,
        source_label,
        created_utc
    )
    VALUES (
        TRIM(p_public_id),
        p_user_id,
        p_computer_id,
        LOWER(TRIM(p_token_hash)),
        p_token_salt,
        v_now_utc,
        v_expires_utc,
        NULL,
        1,
        TRIM(p_source_label),
        v_now_utc
    )
    ON DUPLICATE KEY UPDATE
        public_id = VALUES(public_id),
        token_hash = VALUES(token_hash),
        token_salt = VALUES(token_salt),
        issued_utc = VALUES(issued_utc),
        expires_utc = VALUES(expires_utc),
        revoked_utc = NULL,
        is_active = 1,
        source_label = VALUES(source_label);
    -- `created_utc` is deliberately absent from the update list: it records when this person first signed in on
    -- this machine, and a later sign-in is not that moment.
END$$

DELIMITER ;
