<#
.SYNOPSIS
    Regenerates the mtm_mock master-list files from their file-per-artifact sources.

.DESCRIPTION
    The locked DB ruleset requires each artifact to ship as
    <name>/create.sql (+ rollback.sql) AND to be registered in the database's master lists.
    Hand-maintaining the aggregates drifts, so this script rebuilds them:

      Database/Mock/AllTables.sql     <- Tables/*/create.sql
      Database/Mock/AllSPs.sql        <- StoredProcedures/*/create.sql
      Database/Mock/AllSeeds.sql      <- Seeds/*/create.sql

    Each source file is concatenated VERBATIM (in ordinal name order), which is what makes
    AllSPs.sql valid: the refresh procedures carry their own `DELIMITER $$` / `DELIMITER ;`
    blocks, and the mysql client honours those directives sequentially.

.PARAMETER Check
    Regenerate in memory and fail if any committed master list is out of date.
    Use this in a verification gate.

.EXAMPLE
    pwsh -NoProfile -File Database/CopilotScripts/build_mtm_mock_masters.ps1
    pwsh -NoProfile -File Database/CopilotScripts/build_mtm_mock_masters.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

# This script lives in <repo>/Database/CopilotScripts.
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$mockRoot = Join-Path $repoRoot 'Database/Mock'

function Get-ArtifactBodies {
    param([string]$Folder)

    $dir = Join-Path $mockRoot $Folder
    if (-not (Test-Path $dir)) { return @() }

    Get-ChildItem $dir -Directory | Sort-Object Name | ForEach-Object {
        $create = Join-Path $_.FullName 'create.sql'
        if (Test-Path $create) {
            [pscustomobject]@{
                Name = $_.Name
                Body = (Get-Content -LiteralPath $create -Raw).TrimEnd()
            }
        }
    }
}

function New-MasterList {
    param([string]$Title, [string]$KindDescription, [string]$Folder, [string]$Banner)

    $header = @"
-- Master $KindDescription list: mtm_mock
-- Engine: MySQL 5.7
--
-- GENERATED by Database/CopilotScripts/build_mtm_mock_masters.ps1 — do not edit by hand.
-- Source: Database/Mock/$Folder/<name>/create.sql (concatenated verbatim, ordinal order).
--
-- $Title
"@

    $parts = @($header, '', $Banner)
    foreach ($artifact in (Get-ArtifactBodies -Folder $Folder)) {
        $parts += ''
        $parts += '-- ============================================================'
        $parts += "-- Artifact: $($artifact.Name)"
        $parts += '-- ============================================================'
        $parts += ''
        $parts += $artifact.Body
    }

    ($parts -join "`r`n") + "`r`n"
}

$targets = @(
    @{ Path = 'AllTables.sql'; Content = (New-MasterList -Title 'Registered tables: five mirrors + their stage twins.' -KindDescription 'table' -Folder 'Tables' -Banner "USE mtm_mock;`r`n`r`nSET NAMES utf8mb4;`r`n`r`nSET FOREIGN_KEY_CHECKS = 0;") },
    @{ Path = 'AllSPs.sql'; Content = (New-MasterList -Title 'Registered procedures: sp_visual_<shape>_{get,refresh}.' -KindDescription 'stored-procedure' -Folder 'StoredProcedures' -Banner 'USE mtm_mock;') },
    @{ Path = 'AllSeeds.sql'; Content = (New-MasterList -Title 'Registered seeds: baseline mirror content (is_seed_content = 1).' -KindDescription 'seed' -Folder 'Seeds' -Banner 'USE mtm_mock;') }
)

$stale = @()
foreach ($target in $targets) {
    $full = Join-Path $mockRoot $target.Path
    $existing = if (Test-Path $full) { Get-Content -LiteralPath $full -Raw } else { $null }

    if ($Check) {
        if ($existing -ne $target.Content) { $stale += $target.Path }
        continue
    }

    Set-Content -LiteralPath $full -Value $target.Content -NoNewline -Encoding utf8
    Write-Host "wrote $($target.Path)" -ForegroundColor Green
}

if ($Check) {
    if ($stale.Count -gt 0) {
        Write-Host "Master lists are out of date: $($stale -join ', ')" -ForegroundColor Red
        Write-Host 'Run tools/build_mtm_mock_masters.ps1 to regenerate.'
        exit 1
    }
    Write-Host 'Master lists are up to date.' -ForegroundColor Green
}
